import 'package:flutter/material.dart';
import 'package:law_guide/bookmark_notes.dart';

class ArticlesPage extends StatelessWidget {
  final List<Map<String, String>> articles = [
    {
      "title": "Section 1 - Short Title, Extent, and Commencement",
      "content": "This Act may be called the Information Technology Act, 2000. It extends to the whole of India and applies to any offense or contravention committed outside India by any person. It shall come into force on such date as the Central Government may notify. Nothing in this Act shall apply to documents or transactions specified in the First Schedule, but the Central Government may amend the schedule by notification."
    },
    {
      "title": "Section 2 - Definitions",
      "content": "1. Access – Gaining entry into, instructing, or communicating with a computer system or network.\n2. Addressee – A person intended to receive an electronic record, excluding intermediaries.\n3. Adjudicating Officer – An officer appointed under Section 46 to adjudicate cyber law violations.\n4. Affixing electronic signature – The act of authenticating an electronic record through a digital signature."
    },
    {
      "title": "Section 3 - Authentication of Electronic Records",
      "content": "1. A subscriber may authenticate an electronic record by affixing a digital signature.\n2. The authentication shall be done using an asymmetric crypto system and hash function.\n3. A person can verify an electronic record using the subscriber’s public key."
    },
    {
      "title": "Section 4 - Legal Recognition of Electronic Records",
      "content": "If any law requires a document to be written, typed, or printed, it shall be deemed legally valid if maintained in an electronic form."
    },
    {
      "title": "Section 5 - Legal Recognition of Electronic Signatures",
      "content": "Where a law requires authentication via a signature, an electronic signature shall suffice if affixed as per government-prescribed methods."
    },
    {
      "title": "Section 6 - Use of Electronic Records in Government Agencies",
      "content": "Government agencies may accept electronic records, digital signatures, and e-filings for official use."
    },
    {
      "title": "Section 7 - Retention of Electronic Records",
      "content": "If the law requires records to be maintained, electronic records must be:\n- Accessible for future reference.\n- Stored in a way that ensures data integrity."
    },
    {
      "title": "Section 10A - Validity of Contracts Formed Through Electronic Means",
      "content": "A contract shall not be invalid merely because it was formed electronically."
    },
    {
      "title": "Section 10 - Power to Make Rules for Electronic Signatures",
      "content": "The Central Government may prescribe rules for electronic signatures, including their type, format, affixing method, security measures, and integrity checks."
    },
    {
      "title": "Section 10A - Validity of Contracts Formed Through Electronic Means",
      "content": "Contracts formed using electronic communication (e.g., emails, digital signatures, online transactions) are legally valid and enforceable."
    },
    {
      "title": "Section 11 - Attribution of Electronic Records",
      "content": "An electronic record is attributed to its sender if it was sent by the originator themselves, by a person authorized on their behalf, or automatically generated by their system."
    },
    {
      "title": "Section 12 - Acknowledgment of Receipt of Electronic Record",
      "content": "If an acknowledgment is required, the record is considered not sent until it is acknowledged. Acknowledgment can be given electronically (e.g., email reply, system confirmation)."
    },
    {
      "title": "Section 13 - Time and Place of Dispatch and Receipt of Electronic Record",
      "content": "Dispatch occurs when an electronic record leaves the sender’s control. Receipt occurs when the record enters the recipient’s system and can be retrieved."
    },
    {
      "title": "Section 14 - Secure Electronic Records",
      "content": "If a security procedure is applied to an electronic record, it is considered secure from the time of creation to verification."
    },
    {
      "title": "Section 15 - Secure Electronic Signature",
      "content": "A secure electronic signature is valid if it is exclusively controlled by the signer and can detect any changes after signing."
    },
    {
      "title": "Section 16 - Security Procedures and Practices",
      "content": "The Central Government may prescribe security standards for electronic records and signatures, considering commercial, technical, and legal factors."
    },
    {
      "title": "Section 17 - Appointment of Controller and Other Officers",
      "content": "The Central Government appoints the Controller of Certifying Authorities (CCA) to regulate digital signatures. The CCA has Deputy Controllers and Assistant Controllers to assist."
    },
    {
      "title": "Section 18 - Functions of Controller",
      "content": "The Controller supervises Certifying Authorities (CAs), ensures PKI standards, sets security measures, and regulates digital certificate issuance."
    },
    {
      "title": "Section 19 - Recognition of Foreign Certifying Authorities",
      "content": "Foreign Certifying Authorities (CAs) can be recognized in India if approved by the Central Government. Recognition can be revoked for non-compliance."
    },
    {
      "title": "Section 20 - [Omitted]",
      "content": "This section was removed in the IT (Amendment) Act, 2008."
    },
    {
      "title": "Section 21 - License to Issue Electronic Signature Certificates",
      "content": "Entities issuing digital signature certificates (DSCs) must apply for a license from the Controller of Certifying Authorities (CCA)."
    },
    {
      "title": "Section 22 - Application for License",
      "content": "Applications must include a Certification Practice Statement (CPS), procedures for user identity verification, and a license fee (max ₹25,000)."
    },
    {
      "title": "Section 23 - Renewal of License",
      "content": "Licenses are valid for a prescribed period and must be renewed at least 45 days before expiration."
    },
    {
      "title": "Section 24 - Procedure for Grant or Rejection of License",
      "content": "The CCA can approve or reject an application, but rejection must be preceded by a fair hearing."
    },
    {
      "title": "Section 25 - Suspension of License",
      "content": "The Controller may suspend a Certifying Authority's (CA) license if the CA provides false information, fails security standards, or violates IT Act provisions."
    },
    {
      "title": "Section 26 - Notice of Suspension or Revocation of Licence",
      "content": "If a Certifying Authority's license is suspended or revoked, the Controller must publish a notice in the official database and repositories, ensuring accessibility 24/7 via a website."
    },
    {
      "title": "Section 27 - Power to Delegate",
      "content": "The Controller may delegate his powers in writing to the Deputy Controller, Assistant Controller, or any authorized officer."
    },
    {
      "title": "Section 28 - Power to Investigate Contraventions",
      "content": "The Controller or an authorized officer can investigate violations of the IT Act and has similar powers as income-tax authorities."
    },
    {
      "title": "Section 29 - Access to Computers and Data",
      "content": "Authorized personnel can access any computer system or data if they suspect a contravention of this chapter, requiring cooperation from system operators."
    },
    {
      "title": "Section 30 - Certifying Authority to Follow Certain Procedures",
      "content": "Certifying Authorities must use secure hardware/software, ensure service reliability, maintain data privacy, and publish certificate information."
    },
    {
      "title": "Section 31 - Certifying Authority to Ensure Compliance",
      "content": "Certifying Authorities must ensure all employees comply with the IT Act, rules, and regulations."
    },
    {
      "title": "Section 32 - Display of Licence",
      "content": "Certifying Authorities must display their license prominently at their business premises."
    },
    {
      "title": "Section 33 - Surrender of Licence",
      "content": "If a Certifying Authority's license is suspended or revoked, it must be surrendered immediately, failing which penalties apply."
    },
    {
      "title": "Section 34 - Disclosure",
      "content": "Certifying Authorities must disclose their electronic signature certificates, practice statements, revocation notices, and reliability-impacting facts."
    },
    {
      "title": "Section 35 - Certifying Authority to Issue Electronic Signature Certificate",
      "content": "Any person may apply for an electronic signature certificate with a prescribed fee. The authority can accept or reject applications."
    },
    {
      "title": "Section 36 - Representations Upon Issuance of Digital Signature Certificate",
      "content": "The Certifying Authority must confirm that the issued Digital Signature Certificate is based on accurate representations and complies with the IT Act."
    },
    {
      "title": "Section 37 - Suspension of Digital Signature Certificate",
      "content": "A Certifying Authority may suspend a Digital Signature Certificate upon request or in the public interest, but not beyond 15 days without hearing the subscriber."
    },
    {
      "title": "Section 38 - Revocation of Digital Signature Certificate",
      "content": "A Digital Signature Certificate may be revoked due to false information, the subscriber’s death, insolvency, or security system compromise."
    },
    {
      "title": "Section 39 - Notice of Suspension or Revocation",
      "content": "If a certificate is suspended or revoked, the Certifying Authority must publish the notice in designated repositories."
    },
    {
      "title": "Section 40 - Generating Key Pair",
      "content": "Subscribers must generate a key pair (public and private keys) using a security procedure before accepting a Digital Signature Certificate."
    },
    {
      "title": "Section 41 - Duties of Subscribers",
      "content": "Subscribers must exercise reasonable care to retain control of their private key and take necessary steps to prevent unauthorized access or misuse."
    },
    {
      "title": "Section 42 - Acceptance of Digital Signature Certificate",
      "content": "A subscriber is deemed to have accepted a Digital Signature Certificate if they use it for electronic transactions or fail to object within a reasonable time."
    },
    {
      "title": "Section 43 - Penalty for Damage to Computer, Computer System, etc.",
      "content": "Any person who unauthorizedly accesses, downloads, damages, disrupts, or introduces viruses into a computer system is liable to pay compensation or face legal penalties."
    },
    {
      "title": "Section 43A - Compensation for Failure to Protect Personal Data",
      "content": "Organizations handling sensitive personal data must implement reasonable security practices. Failure to do so resulting in data breaches can lead to liability for compensation."
    },
    {
      "title": "Section 44 - Penalty for Failure to Furnish Information",
      "content": "Any failure to provide information, returns, or documents to authorities as required under the Act can result in financial penalties."
    },
    {
      "title": "Section 45 - Residuary Penalty",
      "content": "For any contravention under the IT Act, 2000 for which no specific penalty is provided, the person shall be liable to pay a penalty up to ₹25,000."
    },
    {
      "title": "Section 46 - Appointment of Adjudicating Officer",
      "content": "The Central Government appoints an Adjudicating Officer to handle disputes related to contraventions of this Act."
    },
    {
      "title": "Section 47 - Factors to be Taken into Account for Adjudication",
      "content": "When determining the amount of compensation or penalty, factors like the nature of the offense, impact, and benefits gained are considered."
    },
    {
      "title": "Section 48 - Cyber Appellate Tribunal",
      "content": "The Cyber Appellate Tribunal is established to hear appeals from decisions of the Adjudicating Officer under the IT Act."
    },
    {
      "title": "Section 49 - Composition of Cyber Appellate Tribunal",
      "content": "The Cyber Appellate Tribunal comprises a Chairperson and other members as appointed by the government."
    },
    {
      "title": "Section 50 - Qualifications for Appointment as Chairperson or Member",
      "content": "The Chairperson of the Cyber Appellate Tribunal must have been a Judge of a High Court or possess special knowledge in IT laws."
    },
    {
      "title": "Section 51 - Term of Office, Salary, and Conditions of Service",
      "content": "The term of office, salary, and conditions of service for members of the Cyber Appellate Tribunal are determined by the Central Government."
    },
    {
      "title": "Section 52 - Resignation and Removal",
      "content": "A member of the Cyber Appellate Tribunal may resign or be removed by the Central Government for proven misconduct or incapacity."
    },
    {
      "title": "Section 53 - Orders Constituting Tribunal to be Final",
      "content": "Any order related to the establishment of the Cyber Appellate Tribunal shall be final and cannot be questioned in any court."
    },
    {
      "title": "Section 54 - Appeal to Cyber Appellate Tribunal",
      "content": "Any person aggrieved by an order of the Adjudicating Officer may appeal to the Cyber Appellate Tribunal within 45 days of the order."
    },
    {
      "title": "Section 55 - Procedure and Powers of the Tribunal",
      "content": "The Cyber Appellate Tribunal has the same powers as a civil court, including summoning individuals and examining evidence under oath."
    },
    
    {
      "title": "Section 56 - Appeal to High Court",
      "content": "Any person dissatisfied with an order of the Cyber Appellate Tribunal may appeal to the High Court within 60 days."
    },
    {
      "title": "Section 57 - Compounding of Contraventions",
      "content": "Certain contraventions under this Act may be settled by an adjudicating officer before formal proceedings begin."
    },
    {
      "title": "Section 58 - Recovery of Penalty",
      "content": "If a person fails to pay a penalty imposed under this Act, it can be recovered as an arrear of land revenue."
    },
    {
      "title": "Section 59 - Chairperson, Members, Officers, and Employees to be Public Servants",
      "content": "All officials of the Cyber Appellate Tribunal, including the Chairperson and members, are deemed public servants."
    },
    {
      "title": "Section 60 - Civil Court Not to Have Jurisdiction",
      "content": "No civil court shall have jurisdiction over matters that the Cyber Appellate Tribunal or adjudicating officer is authorized to handle."
    },
    {
      "title": "Section 61 - Bar of Jurisdiction",
      "content": "No court shall entertain any suit or proceeding on matters that fall within the scope of the IT Act."
    },
    {
      "title": "Section 62 - Appeal to Supreme Court",
      "content": "Any party aggrieved by a decision of the High Court under Section 56 may appeal to the Supreme Court within 90 days."
    },
    {
      "title": "Section 63 - Penalty for Failure to Comply with Tribunal Orders",
      "content": "Failure to comply with orders of the Cyber Appellate Tribunal can lead to imprisonment of up to 3 years or a fine up to ₹1 lakh."
    },
    {
      "title": "Section 64 - Recovery of Penalty as an Arrear of Land Revenue",
      "content": "Any penalty or fine imposed under the IT Act can be collected as land revenue arrears by government authorities."
    },
    {
      "title": "Section 65 - Tampering with Computer Source Documents",
      "content": "Anyone who intentionally tampers with computer source code (like system programs, files, or databases) faces imprisonment of up to 3 years or a fine of up to ₹2 lakh."
    },
    {
      "title": "Section 66 - Hacking with Computer System",
      "content": "Whoever causes wrongful loss or damage by hacking into a computer system may face imprisonment of up to 3 years or a fine up to ₹5 lakh."
    },
    {
      "title": "Section 66A - Punishment for Sending Offensive Messages Through Communication Service",
      "content": "This section was struck down by the Supreme Court in 2015 as unconstitutional. It originally penalized sending offensive messages via electronic means."
    },
    {
      "title": "Section 66B - Punishment for Dishonestly Receiving Stolen Computer Resource",
      "content": "Receiving stolen computer data or devices knowingly can result in imprisonment of up to 3 years or a fine up to ₹1 lakh."
    },
    {
      "title": "Section 66C - Identity Theft",
      "content": "Fraudulently using another person’s electronic signature, password, or any unique identification feature is punishable with imprisonment up to 3 years and a fine up to ₹1 lakh."
    },
    {
      "title": "Section 66D - Cheating by Personation Using Computer Resource",
      "content": "Impersonating someone using electronic means for fraud is punishable with imprisonment up to 3 years and a fine up to ₹1 lakh."
    },
    {
      "title": "Section 66E - Violation of Privacy",
      "content": "Capturing, publishing, or transmitting private images of a person without their consent is punishable with up to 3 years imprisonment and a fine up to ₹2 lakh."
    },
    {
      "title": "Section 66F - Cyber Terrorism",
      "content": "Cyber terrorism, which threatens national security or attacks critical information infrastructure, is punishable with life imprisonment."
    },
    {
      "title": "Section 67 - Publishing or Transmitting Obscene Material in Electronic Form",
      "content": "Publishing or transmitting obscene content online is punishable with imprisonment up to 3 years and a fine up to ₹5 lakh for the first conviction."
    },
    {
      "title": "Section 67A - Publishing or Transmitting Sexually Explicit Material",
      "content": "Publishing or transmitting sexually explicit material online can lead to imprisonment of up to 5 years and a fine up to ₹10 lakh."
    },
    {
      "title": "Section 67B - Child Pornography",
      "content": "Any person who stores, shares, or transmits child sexual content electronically faces imprisonment of up to 7 years and a fine up to ₹10 lakh."
    },
    {
      "title": "Section 68 - Power of Controller to Give Directions",
      "content": "The Controller of Certifying Authorities (CCA) can issue directions to secure the integrity of digital signatures and electronic records."
    },
    {
      "title": "Section 69 - Power to Intercept, Monitor, or Decrypt Information",
      "content": "The government can intercept, monitor, or decrypt electronic communications for national security reasons."
    },
    {
      "title": "Section 69A - Power to Block Public Access to Information",
      "content": "The government can direct any agency or intermediary to block access to any online content in the interest of national security or public order."
    },
    {
      "title": "Section 69B - Power to Monitor and Collect Traffic Data",
      "content": "The government has the authority to monitor and collect network traffic data to enhance cybersecurity and protect national interests."
    },
    {
      "title": "Section 70 - Protected System",
      "content": "Any computer resource designated as a 'protected system' by the government is secured against unauthorized access, with violators facing up to 10 years of imprisonment."
    },
    {
      "title": "Section 71 - Penalty for Misrepresentation",
      "content": "Knowingly making false representations to obtain a license or digital signature certificate is punishable with imprisonment up to 2 years or a fine up to ₹1 lakh."
    },
    {
      "title": "Section 72 - Breach of Confidentiality and Privacy",
      "content": "Unauthorized access to and disclosure of electronic records without consent can result in imprisonment up to 2 years or a fine up to ₹1 lakh."
    },
    {
      "title": "Section 72A - Punishment for Disclosure of Information in Breach of Contract",
      "content": "Service providers who disclose personal data without consent for profit face imprisonment up to 3 years or a fine up to ₹5 lakh."
    },
    {
      "title": "Section 73 - Publishing False Digital Signatures",
      "content": "Publishing a false digital signature certificate with fraudulent intent is punishable with imprisonment up to 2 years or a fine up to ₹1 lakh."
    },
    {
      "title": "Section 74 - Publication for Fraudulent Purposes",
      "content": "Creating, publishing, or making fraudulent electronic records is punishable with imprisonment up to 2 years or a fine up to ₹1 lakh."
    },
    {
      "title": "Section 75 - Act to Apply for Offenses Outside India",
      "content": "The IT Act applies to offenses committed outside India if they involve a computer resource located in India."
    },
    {
      "title": "Section 76 - Confiscation of Computer and Related Resources",
      "content": "Any computer, software, or resource used to commit an offense under the IT Act may be confiscated."
    },
    {
      "title": "Section 77 - Compensation, Penalty, or Confiscation Not to Interfere with Other Punishments",
      "content": "Any penalty imposed under this Act does not prevent additional penalties under other laws."
    },
    {
      "title": "Section 77A - Compounding of Offenses",
      "content": "Certain minor offenses under the IT Act can be settled before formal legal proceedings."
    },
    {
      "title": "Section 77B - Offenses with Imprisonment of Three Years to be Cognizable",
      "content": "Offenses punishable with up to 3 years of imprisonment are cognizable and bailable."
    },
    {
      "title": "Section 78 - Power to Investigate Offenses",
      "content": "A police officer not below the rank of an Inspector has the authority to investigate IT Act offenses."
    },
    {
      "title": "Section 79 - Exemption from Liability of Intermediaries",
      "content": "Intermediaries (such as ISPs and social media platforms) are not liable for user-generated content if they comply with legal guidelines and do not actively promote unlawful acts."
    },
    {
      "title": "Section 80 - Power of Police Officer and Other Officers to Enter, Search, and Arrest",
      "content": "A police officer can enter premises, search, and arrest without warrant if they suspect a cybercrime."
    },
    {
      "title": "Section 81 - Act to Have Overriding Effect",
      "content": "The IT Act overrides any other law when it comes to matters related to electronic transactions and cyber offenses."
    },
    {
      "title": "Section 82 - Constitution of Advisory Committee",
      "content": "An advisory committee may be constituted to provide expert guidance on implementing the IT Act."
    },
    {
      "title": "Section 83 - Chairperson, Members, Officers, and Employees to be Public Servants",
      "content": "All officials under this Act, including adjudicating officers, are considered public servants."
    },
    {
      "title": "Section 84 - Protection of Actions Taken in Good Faith",
      "content": "No legal action can be taken against government officers who act in good faith while enforcing the IT Act."
    },
    {
      "title": "Section 84A - Modes or Methods for Encryption",
      "content": "The government may specify encryption standards to ensure data security."
    },
    {
      "title": "Section 84B - Punishment for Abetting Offenses",
      "content": "Anyone assisting in the commission of an offense under the IT Act faces the same punishment as the principal offender."
    },
    {
      "title": "Section 84C - Punishment for Attempting to Commit Offenses",
      "content": "Attempting to commit an offense under the IT Act is punishable with imprisonment up to 3 years or a fine up to ₹1 lakh."
    },
    {
      "title": "Section 85 - Liability of Companies",
      "content": "If a company commits an offense under the IT Act, persons responsible for its conduct (e.g., directors) may also be held liable."
    },
    {
      "title": "Section 86 - Removal of Difficulties",
      "content": "The central government may make necessary amendments to remove difficulties in implementing the IT Act."
    },
    {
      "title": "Section 87 - Power of Central Government to Make Rules",
      "content": "The central government can make rules to regulate digital signatures, cybersecurity, and IT-related offenses."
    },
    {
      "title": "Section 88 - Constitution of Cyber Regulations Advisory Committee",
      "content": "A Cyber Regulations Advisory Committee may be set up to recommend improvements to cyber laws."
    },
    {
      "title": "Section 89 - Power of Controller to Make Regulations",
      "content": "The Controller of Certifying Authorities (CCA) has the power to issue regulations regarding digital signatures and cybersecurity."
    },
    {
      "title": "Section 90 - Power to Remove Difficulties",
      "content": "The government has the authority to amend the IT Act provisions if they cause practical implementation issues."
    }

  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("IT Act, 2000 - Articles"),
        backgroundColor: Colors.brown.shade300,
      ),
      body: ListView.builder(
        itemCount: articles.length,
        itemBuilder: (context, index) {
          return Card(
            margin: EdgeInsets.symmetric(horizontal: 10, vertical: 5),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
            child: ExpansionTile(
              title: Text(
                articles[index]["title"]!,
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
              children: [
                Padding(
                  padding: EdgeInsets.all(16),
                  child: Text(
                    articles[index]["content"]!,
                    style: TextStyle(fontSize: 14),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}
