// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7W3IKD3V2uiC1VgY_uhH-MUd2SSPl8c8',
    appId: '1:440538011450:web:53168e0ac04997c8262203',
    messagingSenderId: '440538011450',
    projectId: 'lawguide-e886b',
    authDomain: 'lawguide-e886b.firebaseapp.com',
    storageBucket: 'lawguide-e886b.firebasestorage.app',
    measurementId: 'G-DXB9JBTQ09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqSKauFVK6cCYlZixV8IxUO4yxmr1f_oM',
    appId: '1:440538011450:android:10bf12df9246f558262203',
    messagingSenderId: '440538011450',
    projectId: 'lawguide-e886b',
    storageBucket: 'lawguide-e886b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7W3IKD3V2uiC1VgY_uhH-MUd2SSPl8c8',
    appId: '1:440538011450:web:4acadb2c433db45d262203',
    messagingSenderId: '440538011450',
    projectId: 'lawguide-e886b',
    authDomain: 'lawguide-e886b.firebaseapp.com',
    storageBucket: 'lawguide-e886b.firebasestorage.app',
    measurementId: 'G-Z5CXKXQS15',
  );
}
